- CONTRIBUTING.md
- README.md
- Updated Readme
- Updated contributing.md
> Added guidelines for app contribution

- .all-contributorsrc
- README.md
Reverts Atri-Labs/atrilabs-engine#289
> Revert "docs: add jakebolam as a contributor for test, and code"

- packages/app-page-layer/src/PageEditor.tsx
- packages/app-page-layer/src/components/CreateFolder.tsx
- packages/app-page-layer/src/components/CreatePage.tsx
- packages/app-page-layer/src/components/PageTable.tsx
- packages/app-page-layer/src/components/UpdateFolder.tsx
- packages/app-page-layer/src/components/UpdatePage.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Input/Input.tsx
**Reference**
closes #355 
**Describe the pull request**
These guardrails are only applied in the frontend.
> closes #355

- packages/canvas-runtime-utils/src/utils.ts
- packages/component-style-layer/src/TabBody.tsx
- packages/component-style-layer/src/hooks/useShowTab.ts
- packages/component-style-layer/src/index.tsx
- packages/component-style-layer/src/utils.ts
**Reference**
close #357 
**Describe the pull request**
Existing components of a page are scanned to find duplicate alias.
> close #357 duplicate alias warning

- packages/app-template-layer/src/hooks/useListenCopyPaste.tsx
- packages/canvas-runtime/src/decorators/CanvasActivityDecorator.tsx
- packages/manage-canvas-runtime-layer/src/hooks/useDeleteKey.ts
- packages/undo-redo-layer/src/index.tsx
**Reference**
fixes #348 
**Describe the pull request**
Fixes a bug where Ctrl C and Ctrl V were not working in Windows and Linux.
> closes #348

- packages/app-generator/templates/python-app/Pipfile
Fixed FastApi version to 0.84.0
> Fixed FastApi version to 0.84.0

- packages/undo-redo-layer/src/hooks/useStoreUndoRedoEvents.ts
Undo record for template events
> undo record for template events

- packages/component-style-layer/src/components/miscellaneous/Miscellaneous.tsx
fixes #210 
Removed the duplicate options in cursor dropdown menu.
> fixes #210

- packages/canvas-runtime-utils/src/templateEvents.ts
- packages/forest/src/types.ts
- packages/undo-redo-layer/src/hooks/useStoreUndoRedoEvents.ts
Added a new field in the meta to identify the topmost component during copy-paste.
> bugfix: template events can be undo in series

- packages/app-page-layer/src/components/CreateFolder.tsx
- packages/app-page-layer/src/components/CreatePage.tsx
- packages/app-page-layer/src/components/UpdateFolder.tsx
- packages/app-page-layer/src/components/UpdatePage.tsx
> fixes #386

- packages/server-client/src/ipc-server/server.ts
- packages/server-client/src/ipc-server/types.ts
- python-packages/atri/src/atri/commands/connect_local.py
closes #71 
The SOCKET.IO protocol is not clear whether we need to return some data on every client/server request.
> closes #71

- packages/react-component-manifests/src/manifests/Dropdown/Dropdown.tsx
- packages/react-component-manifests/src/manifests/Radio/Radio.tsx
- packages/react-component-manifests/src/manifests/Table/Table.tsx
- packages/react-component-manifests/src/manifests/charts/AreaChart/AreaChart.tsx
- packages/react-component-manifests/src/manifests/charts/BarChart/BarChart.tsx
- packages/react-component-manifests/src/manifests/charts/CandleStick/CandleStick.tsx
- packages/react-component-manifests/src/manifests/charts/HistogramChart/HistogramChart.tsx
- packages/react-component-manifests/src/manifests/charts/LineChart/LineChart.tsx
- packages/react-component-manifests/src/manifests/charts/PieChart/PieChart.tsx
- packages/react-component-manifests/src/manifests/charts/ScatterChart/ScatterChart.tsx
fixes #396 
This bug is due to a recent change in the specification of how we write draggable components. Due to a change in the specification, the code for some of the components needed to be updated which we missed. This change in specification was to resolve the the issues covererd in PR #270
> Fix broken components

- packages/forest/__tests__/forest.spec.ts
- packages/forest/__tests__/forestDefExample.ts
- packages/forest/src/forest.ts
- packages/forest/tsconfig.json
The tree ids are replaced with real tree ids.
> tests uses real tree ids

- python-packages/atri/src/atri/commands/open_exe.py
> added quotes in atri call

- packages/core/src/types.tsx
- packages/scripts/src/tasks/dev/dev.ts
- packages/server-client/src/file-server/index.ts
- packages/server-client/src/websocket/client.ts
- packages/server-client/src/websocket/server.ts
- packages/webapp-builder/package.json
- packages/webapp-builder/src/tool.config.js
- python-packages/atri/src/atri/cli.py
- python-packages/atri/src/atri/find_app_root.py
- python-packages/atri/src/atri/utils/setup_env.py
> Editors authenticate using project id

- packages/app-generator/src/react-app-template-manager/index.ts
- packages/undo-redo-layer/src/hooks/useStoreUndoRedoEvents.ts
fixes #449 
Sort the maxWidth in reverse order.
> Fix breakpoint priority

- made-with-atri/PR_template_apps.md
A simple calorie tracker app made using the Atri framework for Hacktoberfest'22. Closes #246
Co-authors:
> Calorie tracker app. Closes #246

- .all-contributorsrc
- README.md
Reverts Atri-Labs/atrilabs-engine#475
> Revert "docs: add awdhesh-kumar27 as a contributor for bug"

- packages/canvas-runtime/src/decorators/UnlockCanvasActivityMachineDecorator.tsx
- packages/webapp-builder/package.json
- packages/webapp-builder/src/tool.config.js
> created a flag for comp dev mode

- packages/canvas-runtime/src/Canvas.tsx
- packages/canvas-runtime/src/HintOverlay.tsx
- packages/canvas-runtime/src/hooks/useHintOverlays.tsx
Fix the scrollbar problem in the browser as shown in the pictures.
> Fix canvas iframe

- packages/component-list-layer/src/utils/manifests.ts
- packages/react-component-manifests/src/manifest.config.js
- packages/react-component-manifests/src/manifests/Modal/Modal.css
- packages/react-component-manifests/src/manifests/Modal/Modal.tsx
Add reference to a related issue that this pull request is addressing. For example, fixes #430 
This PR intends to add Modal component into the editor
Co-authors:
> Added Modal component

- .gitignore
- packages/app-design-layer/src/BaseContainer.tsx
- packages/asset-manager-layer/src/index.tsx
- packages/component-style-layer/src/components/background/Background.tsx
- packages/component-style-layer/src/components/border/Border.tsx
- packages/component-style-layer/src/components/css2display/Css2Display.tsx
- packages/component-style-layer/src/components/flexchild/FlexChild.tsx
- packages/component-style-layer/src/components/layout/Layout.tsx
- packages/component-style-layer/src/components/miscellaneous/Miscellaneous.tsx
- packages/component-style-layer/src/components/outline/Outline.tsx
- packages/component-style-layer/src/components/position/Position.tsx
- packages/component-style-layer/src/components/size/Size.tsx
- packages/component-style-layer/src/components/spacing/SpacingProperty.tsx
- packages/component-style-layer/src/components/typography/Typography.tsx
- packages/design-system/src/components/IconMenu/IconMenu.tsx
> Add pointer style for all the header icons and right hand side style dropdowns.

- packages/component-list-layer/src/utils/manifests.ts
- packages/react-component-manifests/src/manifest.config.js
- packages/react-component-manifests/src/manifests/Form/Form.css
- packages/react-component-manifests/src/manifests/Form/Form.tsx
Add reference to a related issue that this pull request is addressing. For example, fixes #431 
This PR intends to add Form component into the codebase
Co-authors:
> Form component added into Atri editor

- packages/component-list-layer/src/utils/manifests.ts
- packages/react-component-manifests/src/manifest.config.js
- packages/react-component-manifests/src/manifests/charts/AreaChart/AreaChart.tsx
- packages/react-component-manifests/src/manifests/charts/BarChart/BarChart.tsx
- packages/react-component-manifests/src/manifests/charts/HistogramChart/HistogramChart.tsx
- packages/react-component-manifests/src/manifests/charts/LineChart/LineChart.tsx
- packages/react-component-manifests/src/manifests/charts/RadialbarChart/RadiadbarChart.tsx
Added Radial Bar Chart component and support for Cartesian-Grid in Line, Area, and Bar Charts
> Radialbarchart

- packages/canvas-runtime/src/hooks/useHintOverlays.tsx
> 🐞 Some overlays (left, right, top) do not appear #551

- packages/react-component-manifests/src/manifest.config.js
- packages/react-component-manifests/src/manifests/Accordion/Accordion.tsx
- packages/react-component-manifests/src/manifests/Carousel/Carousel.tsx
- packages/react-component-manifests/src/manifests/Dropdown/Dropdown.tsx
- packages/react-component-manifests/src/manifests/Form/Form.tsx
- packages/react-component-manifests/src/manifests/Step/Step.tsx
Add reference to a related issue that this pull request is addressing. For example, fixes #603 
This PR implements `array_map` in step, accordion, dropdown and carousel and implements `array_typed_map` in form
Co-authors:
> Refactor custom props

- packages/component-style-layer/src/components/position/Position.tsx
- packages/component-style-layer/src/components/spacing/SpacingProperty.tsx
Add reference to a related issue that this pull request is addressing. For example, fixes #495 
This PR intends to add the ability to change the CSS units in Position and Spacing
Co-authors:
> Implemented ability to change CSS units in Spacing and Position

- made-with-atri/TrackDash.md
A Simple UI To-Do list which lets you add tasks, close them and then delete. Closes #234
Co-authors:
> Adding a new project.

- packages/commands-builder/src/utils/extractParams.ts
- packages/commands/package.json
- packages/commands/src/commons/maps.ts
- packages/commands/src/scripts/build-atri-app/buildClientSide.ts
- packages/commands/src/scripts/serve/routes/exposeStaticDirectories.ts
- packages/commands/src/scripts/serve/serve.ts
- packages/commands/src/scripts/serve/utils/readClientDirectory.ts
- yarn.lock
> JS compression done

- packages/component-style-layer/src/components/commons/ArrayLabel.tsx
- packages/component-style-layer/src/components/commons/ArrayPropertyContainer.tsx
- packages/component-style-layer/src/components/number-list/NumberList.tsx
- packages/component-style-layer/src/components/position/Position.tsx
- packages/component-style-layer/src/components/position/TransformSelector.tsx
- packages/component-style-layer/src/types.ts
> transform style property

- packages/compat/src/fix-events.ts
- packages/compat/src/index.ts
- packages/compat/src/types.ts
> added fix-events.ts

- packages/react-component-manifests/src/manifests/Accordion/Accordion.tsx
- packages/react-component-manifests/src/manifests/Alert/Alert.tsx
- packages/react-component-manifests/src/manifests/Breadcrumb/Breadcrumb.tsx
- packages/react-component-manifests/src/manifests/Card/Card.manifest.ts
- packages/react-component-manifests/src/manifests/Card/Card.tsx
- packages/react-component-manifests/src/manifests/Cascader/Cascader.manifest.ts
- packages/react-component-manifests/src/manifests/Countdown/Countdown.manifest.ts
- packages/react-component-manifests/src/manifests/DatePicker/DatePicker.manifest.ts
- packages/react-component-manifests/src/manifests/Drawer/Drawer.manifest.ts
- packages/react-component-manifests/src/manifests/InputNumber/InputNumber.manifest.ts
- packages/react-component-manifests/src/manifests/Modal/Modal.manifest.ts
- packages/react-component-manifests/src/manifests/Radio/Radio.manifest.ts
- packages/react-component-manifests/src/manifests/Search/Search.manifest.ts
- packages/react-component-manifests/src/manifests/Select/Select.manifest.ts
- packages/react-component-manifests/src/manifests/Slider/Slider.manifest.ts
- packages/react-component-manifests/src/manifests/Slider/Slider.tsx
- packages/react-component-manifests/src/manifests/Statistic/Statistic.manifest.ts
- packages/react-component-manifests/src/manifests/Step/Step.manifest.ts
- packages/react-component-manifests/src/manifests/Timeline/Timeline.manifest.ts
- packages/react-component-manifests/src/manifests/UnorderedList/UnorderedList.manifest.ts
- packages/react-component-manifests/src/manifests/Upload/Upload.manifest.ts
> Changes for the styles manifest config to false those are not working
